### ISSUE TITLE
Sprint 1 Documentation

### ISSUE THREAD

**Issue by mattirizarry** [irizarry-development/wku-filmatrix#16]
# Format Requirements

Dr. Galloway's Rubric [here](https://drive.google.com/file/d/19e7UoErIZUO5abQjXgW6Rbj7huWxMCml/view)

- [x] Images / tables / charts have captions
- [x] No large amounts of blank space
- [x] Minimum usage of bullets / indentation
- [x] No grammatical errors

### Cover Page

- [x] Project Title
- [x] Course ID
- [x] Sprint number and date submitted
- [x] Group member names and WKU email addresses
- [x] Client name

### Length Requirements
8 pages minimum (excluding cover page and TOC)

### Content Requirements

- [x] #18 
- [x] #19 
- [x] #20 
- [x] #21 
- [x] #22 
- [x] #23 

### Length Requirements
2 pages minimum (excluding cover page and TOC)

### Content Requirements

- [x] #24 
- [x] #25
- [x] #26 
- [x] #27 
- [x] #28 
- [x] #29 
- [x] #30
