### ISSUE TITLE
Sprint 2 Documentation

### ISSUE THREAD

**Issue by mattirizarry** [irizarry-development/wku-filmatrix#46]
# Format Requirements

- [ ] Images / tables / charts have captions
- [ ] No large amount of blank space
- [ ] Minimum use of bullet points / indentation of paragraphs
- [ ] No grammatical errors

## Cover Page

- [ ] Project Title
- [ ] Course ID
- [ ] Sprint number and date submitted
- [ ] Group member names and WKU email addresses
- [ ] Client name

### Length Requirements 

16 pages minimum (excluding cover page and TOC)

### Content Requirements

- [x] #56
- [x] #57
- [x] #58
- [x] #59
- [x] #60
- [ ] #61
- [ ] #62
- [x] #63
- [x] #64
- [x] #65

### Length Requirements

4 page minimum (excluding cover page and TOC)

### Content Requirements

- [x] #66
- [x] #67
- [x] #68
- [x] #69
- [x] #70
- [x] #71
- [x] #72
